export enum BookingStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum BookingErrorCode {
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_INACTIVE = 'ROOM_INACTIVE',
  OVERLAPPING_BOOKING = 'OVERLAPPING_BOOKING',
  PAST_TIME_INVALID = 'PAST_TIME_INVALID',
  PAST_TIME = 'PAST_TIME',
  EXCEEDS_CAPACITY = 'EXCEEDS_CAPACITY',
  CAPACITY_EXCEEDED = 'CAPACITY_EXCEEDED',
  DURATION_INVALID = 'DURATION_INVALID',
  OUTSIDE_BUSINESS_HOURS = 'OUTSIDE_BUSINESS_HOURS',
  WEEKEND_NOT_ALLOWED = 'WEEKEND_NOT_ALLOWED',
  INVALID_REQUEST = 'INVALID_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
